Feature/curl binary
greenhousecode/create-meh-app pull request #43
Opened 2020-10-26 16:27 UTC by IamRobin

Remove binary from the project and curl it when setting up the project.

2020-10-27 07:46 UTC, rick-stevens requested changes

2020-10-27 07:46 UTC, rick-stevens commented on src/actions/installDependencies.js
> +        '&& (chmod +x ./tools/envhelper)',
Waarom in parentheses?

2020-10-27 07:46 UTC, rick-stevens commented on src/actions/installDependencies.js
> +        'https://cdn.greenhousegroup.com/ghg-nl/meh/binaries/envhelper-latest',
Deze URL werkt nog niet
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Messag$
```

2020-10-27 07:46 UTC, rick-stevens commented on src/templates/default/README.md
> +```
Qua semantics zou ik dit stuk in een `>` zetten onderaan scripts als een soort sidenote. Nu lijkt het een script terwijl het geen script is.

2020-10-27 13:47 UTC, IamRobin commented on src/templates/default/README.md
> +```
Ohhw dit kan nu trouwens weg. Ik had het eerst niet als postinstall script. Het was eerst onderdeel van `installDependencies.js` en toen was dit wel nodig. Ik haal het helemaal weg. Agree?

2020-10-28 13:50 UTC, rick-stevens requested changes
Ik zou de tools dir dan ook niet mee committen (.gitkeep), en `tools` gewoon toevoegen aan de .gitignore. Haal jij de overbodige docs ook nog even weg?

2020-10-28 16:11 UTC, IamRobin commented on src/templates/default/package.json
> +    "postinstall": "curl -o ./tools/envhelper https://cdn.greenhousegroup.com/ghg-nl/meh/binaries/envhelper-latest && chmod +x ./tools/envhelper"
Ah die wist ik niet. Ik dacht dat je met curl -o altijd naar een bestaande map moest verwijzen

2020-10-29 08:24 UTC, rick-stevens commented on src/templates/default/_gitignore
> +tools
Ik mis hier nog een line ending (kun je autofixen met deze default settings voor VSCode: https://gitlab.com/-/snippets/2003889)

2020-10-29 08:28 UTC, rick-stevens approved these changes
Voeg jij nog de line ending toe?

2020-11-03 17:10 UTC, closed without merging